### ISSUE TITLE
Enable/disable option not working for shared API GW

### ISSUE THREAD

**Issue by GaaraZhu** [DianaIonita/serverless-api-gateway-caching#103]
When using shared API GW, the global configuration `apiGatewayCaching.enable` and endpoint configuration `caching.enable` doesn't work as expected. As long as the cache is enabled for shared API GW, it will be enabled for all individual endpoints in it.

Wondering is those two options designed only for dedicated API GWs? Thanks

**Comment by DianaIonita** [comment]
Hi @GaaraZhu,

Thanks for your question.

You can have endpoints split across multiple serverless projects, but all pointing to the same API Gateway. [This documentation](https://www.serverless.com/framework/docs/providers/aws/events/apigateway/#share-api-gateway-and-api-resources) shows how you can reference an already existing API Gateway within a serverless project.

When using this plugin, it is expected that you would apply it to the project where your API Gateway configuration lives, so that it can enable/disable caching across the stage.

Any endpoints that are deployed via other projects that reference this API Gateway would, by default, inherit their caching settings from the configuration in the main API Gateway project, even when they don't themselves use the caching plugin.

When you add the caching plugin to these endpoint projects, you would need to specify `apiGatewayIsShared: true` so that it doesn't apply this project's specific settings to the main API Gateway.

Here's an example of how you might use it:

Main API Gateway `serverless.yml`:
```yml
plugins:
  - serverless-api-gateway-caching

custom:
  # all endpoints deployed to this gateway inherit these settings by default
  apiGatewayCaching:
    enabled: false # all endpoints by default have caching disabled
```

Another project's `serverless.yml` which only deploys endpoints that reference the main API Gateway:
```yml
plugins:
  - serverless-api-gateway-caching

custom:
  apiGatewayCaching:
    enabled: true # this enables caching for endpoints in this project (each endpoint must also set caching: enabled to true)
    apiGatewayIsShared: true

functions:
  # caching disabled, it must be explicitly enabled
  createUser:
    handler: createUser.handle
    events:
      - http:
          path: /users
          method: post

  getUsers:
    handler: getUsers.handle
    events:
      - http:
          path: /users
          method: get
          caching:
            enabled: true # enables caching for this endpoint
```

I hope this makes sense.
If your use case is different to the above, please provide some more detail about your configuration.

**Comment by GaaraZhu** [comment]
Thanks @DianaIonita for such a detailed reply. This is very helpful. Previously we only applied the plugin in the endpoint config not the shared API GW. I'll have another try and let you know whether it works or not. Thanks

**Comment by GaaraZhu** [comment]
@DianaIonita We just tried with above solution, what we found is after we applied below configure to the main API GW, the cache has been disabled for the whole API GW(stage->settings->cache settings). After we enabled it in our service for the endpoint, we checked both in Postman for the request duration and checked the metrics in Cloudwatch, either shows there is a cache for the endpoint.

Our main API GW configuration:
```
plugins:
  - serverless-api-gateway-caching

custom:
  apiGatewayCaching:
    restApiId: ${cf:core-layer-${self:provider.stage}.apiGatewayRestApiId}
    enabled: false # all endpoints by default have caching disabled
```

Our service endpoint configuration:
```
      - http:
          private: true
          path: ${self:custom.api.urls.accountsGet}
          method: get
          cors: true
          request:
            parameters:
              paths:
                customerId: true
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.path.customerId
 ...
plugins:
  - serverless-api-gateway-caching

custom:
  apiGatewayCaching:
    enabled: true
    apiGatewayIsShared: true
```

**Comment by DianaIonita** [comment]
Hi @GaaraZhu,

I reviewed the setup that I'm currently using and the main API Gateway settings are as follows:

```
custom:
  apiGatewayCaching:
    enabled: true # create an API cache
    ttlInSeconds: 0 # but don't cache responses by default (individual endpoints can override this)
```

This isn't particularly easy to figure out, I also made the mistake of trying to do so without an example.
I'll add this to the plugin readme.
