### ISSUE TITLE
Upgrade from 1.7.5 to 1.8.0 breaking API Gateway endpoint

### ISSUE THREAD

**Issue by smingins** [DianaIonita/serverless-api-gateway-caching#109]
Hi

The changes here https://github.com/DianaIonita/serverless-api-gateway-caching/pull/107 are setting these request parameters and breaking the API endpoint that has them applied.  The Cloudformation template now has:

```
"RequestParameters":
  {
    "integration.request.header.Origin": "method.request.header.Origin",
    "integration.request.header.origin": "method.request.header.origin",
  },

```
When before it was:

```
"RequestParameters": {}
```

The serverless.yml entry looks like:

```
  health:
    handler: src/api/v1/health.handler
    events:
      - http:
          path: v1/health
          method: get
          cors: true
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.header.Origin
              - name: request.header.origin
```

Is there something that I can do to fix this?
