### ISSUE TITLE
Caching yields no results when adding cache key parameter method.request.Authorization

### ISSUE THREAD

**Issue by eggboy0** [DianaIonita/serverless-api-gateway-caching#110]
I have the following in serverless.yml:

GET method that uses Lambda Proxy Integration:
```
caching:
            enabled: true
            cacheKeyParameters:
              - name: request.header.Authorization
```

However, this always yields no results when there should be results. Any ideas?
