### ISSUE TITLE
Support on cache by body on POST request

### ISSUE THREAD

**Issue by leeboy1984** [DianaIonita/serverless-api-gateway-caching#115]
Hi, 

I'm getting "Internal Server Error" when I'm trying to configure a POST request.

Here is my function definition
```yaml
postCached:
    handler: src/handlers/postCached.handler
    events:
      - http:
          path: /cached/test
          method: post
          cors: true
          caching:
            enabled: true
            cacheKeyParameters:
              - name: integration.request.header.bodyValue
                mappedFrom: method.request.body
```

And a body example:
```json
{
  "email": "foo@bar.xyz"
}
```

What is wrong?

**Comment by DianaIonita** [comment]
Hi @leeboy1984,

Could you please check if your endpoint works when the caching plugin is not used? For example, you could remove it from the `serverless.yml` `plugins` section.

Thanks.

**Comment by leeboy1984** [comment]
Yes! It works perfectly if I remove the cache config or remove the plugin

**Comment by DianaIonita** [comment]
Hi @leeboy1984,

Could you please try adding `integration: lambda` to your event?

For example:
```yml
events:
  - http:
      path: /cached/test
      method: post
      integration: lambda
```
