### ISSUE TITLE
Unable to set cache key from the request context

### ISSUE THREAD

**Issue by vmitsek-amplify** [DianaIonita/serverless-api-gateway-caching#135]
When I trying to set cache key from request context the plugin always prepends `method` which leads to validation error during CF stack update: `Invalid mapping expression specified: method.context.authorizer.principalId]`. Is that a bug or I just using wrong mapping?
[AWS documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/request-response-data-mappings.html#:~:text=stageVariables.VARIABLE_NAME-,Context,-variables) says that path to context does not start with `method`

```
caching:
    enabled: ${self:custom.config.is_caching_enabled}
    ttlInSeconds: 900
    cacheKeyParameters:
        - name: context.authorizer.principalId
```
