### ISSUE TITLE
headers caching for multi-tenant

### ISSUE THREAD

**Issue by fernandohonig** [DianaIonita/serverless-api-gateway-caching#137]
Hi! 
We have a SaaS app and we use a custom header to define the customer-id and send that to the APIs we have.
In every request, we have that customer-id header. 
When I enable caching, data from one customer is shown in another customer, like it's not respecting the customer-id key I set in every function.

For instance:

```
    events:
      - http:
          method: GET
          request:
            parameters:
              querystrings:
                module: true
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.header.Stack-Org
              - name: request.querystring.module
```

What am I doing wrong?.  Thanks!

**Comment by DianaIonita** [comment]
Hi @fernandohonig,

Thanks for raising the issue.
Can you please confirm via the AWS Console that caching is enabled for the API Gateway you're using in this project and that the `customer-id` cache key parameter is set?

For example:

![image](https://github.com/DianaIonita/serverless-api-gateway-caching/assets/2750493/1a5b0f6b-b9a3-4d97-850c-2be965b097f9)

here I set a "limit" query string parameter:
![image](https://github.com/DianaIonita/serverless-api-gateway-caching/assets/2750493/923ee84f-0702-478f-82c8-f230a21ada29)

**Comment by fernandohonig** [comment]
Hi @DianaIonita, thanks for taking the time.

Yes, it’s enabled but the difference is that the caching is not on the query string as shown in your picture, but in the request headers.

**Comment by fernandohonig** [comment]
@DianaIonita any ideas about this?. Thanks.

**Comment by DianaIonita** [comment]
Hi @fernandohonig,

Apologies for the delay. Here's what I tried:
- I installed the [latest version](https://github.com/DianaIonita/serverless-api-gateway-caching/releases/tag/1.10.4) of this caching plugin
- I enabled caching:
```yml
plugins:
  - serverless-api-gateway-caching

custom:
  apiGatewayCaching:
    enabled: true
```
- I added it to my function:

```yml
functions:
  list-cats:
    handler: rest_api/cats/get/handler.handle
    events:
      - http:
          path: /cats
          method: get
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.header.customer-id
```

- when listing the response, I also added a response timestamp, so it generates a fresh one each time the lambda is invoked

- then I tested if it worked:
  - when calling this endpoint with header `customer-id=123`, it returns response timestamp A
  - calling it with header `customer-id=456` returns response timestamp B
  - calling it again with header `customer-id=123` returns response timestamp A again, which is expected
  - calling it again with header `customer-id=456` returns response timestamp B, also as expected

In your configuration, can you tell if anything differs from what I tried?
