### ISSUE TITLE
Caching on Path

### ISSUE THREAD

**Issue by RALifeCoach** [DianaIonita/serverless-api-gateway-caching#14]
Is there a way to turn on caching for the path?

**Comment by RALifeCoach** [comment]
Yes. Now how do I set up caching based on path and path parameter. For example, I have 
…/en/pool/{PoolId} and
…/en/player{PolId}.

I need to cache based on:
-name: /en/pool - request.path??? Request.path.url???
-name: request.path.poolId

and

-name: /en/player
-name: poolId

**Comment by RALifeCoach** [comment]
That isn’t working. I get the same file regardless of the final qualifier. I also tried adding the final qualifier, but still no success.

**Comment by thebeatlecoder** [comment]
My bad, I was wrong about this. If you have separate lambda functions serving each URL (which is the pattern we use), you can do this:

```yml
functions:
  get-pool:
    handler: rest_api/pool/get/handler.handle
    events:
      - http:
          path: /en/pool/{poolId}
          method: get
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.path.poold

  get-player:
    handler: rest_api/player/get/handler.handle
    events:
      - http:
          path: /en/player/{poolId}
          method: get
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.path.poold

```

I'm not sure how to do it if you have one lambda function serving all of your URLs. Is that what you have currently?

**Comment by thebeatlecoder** [comment]
If you do have a single lambda function serving all requests, maybe you can do this:

```yml
http-get-requests:
    handler: rest_api/get/handler.handle
    events:
      - http:
          path: /{shortUrl}
          method: get
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.path.shortUrl
```

I haven't tried this personally but it looks like it should work.

**Comment by thebeatlecoder** [comment]
If you do  have a single lambda function serving all our your URLs, this should work. I just tired it and it worked for me:

```yml
proxy-http-get:
    handler: rest_api/proxy/handler.handle
    events:
      - http:
          path:  /{proxy+}
          method: get
          caching:
            enabled: true
            ttlInSeconds: 3600
            cacheKeyParameters:
              - name: request.path.proxy
```

**Comment by RALifeCoach** [comment]
This is what I started with. And for both pool and player, the poolId is ignored and the first read sets the cache and that is the file returned for subsequent reads.

**Comment by RALifeCoach** [comment]
```
service: service-name

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  vpc:
    securityGroupIds:
      - ${file(./config/config.${self:provider.stage}.api.json):vpcSecurityGroup}
    subnetIds:
      - ${file(./config/config.${self:provider.stage}.api.json):vpcSubnet}
  environment:
    MODE: 'api'
    DB_HOST: ${file(./config/config.${self:provider.stage}.api.json):dbHost}
    DB_USER: ${file(./config/config.${self:provider.stage}.api.json):dbUser}
    DB_PASSWORD: ${file(./config/config.${self:provider.stage}.api.json):dbPassword}
    LOG_LEVEL: ${file(./config/config.${self:provider.stage}.api.json):logLevel}

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-api-gateway-caching
  - serverless-plugin-warmup

custom:
  apiGatewayCaching:
    enabled: true
    clusterSize: '0.5' # defaults to '0.5'
    ttlInSeconds: 600 # defaults to the maximum allowed: 3600
    perKeyInvalidation:
      requireAuthorization: true # default is true
      handleUnauthorizedRequests: IgnoreWithWarning # default is "IgnoreWithWarning"
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'npm'

functions:
  championship:
    handler: src/api/index.championship
    warmup: true
    events:
      - http:
          path: championship/{type}
          method: get
          cors: true
          request:
            parameters:
              paths:
                type: true
          caching:
            enabled: true
            ttlInSeconds: 300
            perKeyInvalidation:
              requireAuthorization: true
              handleUnauthorizedRequests: Ignore
            cacheKeyParameters:
              - name: request.path.type
  competition:
    handler: src/api/index.competition
    warmup: true
    events:
      - http:
          path: competition/{champId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                champId: true
          caching:
            enabled: true
            ttlInSeconds: 300
            perKeyInvalidation:
              requireAuthorization: true
              handleUnauthorizedRequests: Ignore
            cacheKeyParameters:
              - name: request.path.champId
  keyCompetition:
    handler: src/api/index.keyCompetition
    warmup: true
    events:
      - http:
          path: keyCompetition/{key}
          method: get
          cors: true
          request:
            parameters:
              paths:
                key: true
          caching:
            enabled: true
            ttlInSeconds: 300
            perKeyInvalidation:
              requireAuthorization: true
              handleUnauthorizedRequests: Ignore
            cacheKeyParameters:
              - name: request.path.key
  competitionPool:
    handler: src/api/index.competitionPool
    warmup: true
    events:
      - http:
          path: competitionPool/{competitionId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                competitionId: true
          caching:
            enabled: true
            ttlInSeconds: 300
            perKeyInvalidation:
              requireAuthorization: true
              handleUnauthorizedRequests: Ignore
            cacheKeyParameters:
              - name: request.path.competitionId
  pool:
    handler: src/api/index.pool
    warmup: true
    events:
      - http:
          path: pool/{poolId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                poolId: true
          caching:
            enabled: true
            ttlInSeconds: 300
            perKeyInvalidation:
              requireAuthorization: true
              handleUnauthorizedRequests: Ignore
            cacheKeyParameters:
              - name: request.path.shortUrl
              - name: request.path.poolId
  player:
    handler: src/api/index.player
    warmup: true
    events:
      - http:
          path: player/{poolId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                poolId: true
          caching:
            enabled: true
            ttlInSeconds: 300
            perKeyInvalidation:
              requireAuthorization: true
              handleUnauthorizedRequests: Ignore
            cacheKeyParameters:
              - name: request.path.shortUrl
              - name: request.path.poolId
```
