### ISSUE TITLE
No Rest API found. Caching settings will not be updated.

### ISSUE THREAD

**Issue by dodoshanti** [DianaIonita/serverless-api-gateway-caching#15]
Hi
I get the above message when trying to use the plugin. Here is my serverless.yml

```
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'test'}
  region: eu-west-1

functions:
  app:
    handler: src/index.handler
    events:
      - http:
          path: 'products/{id}'
          method: 'GET'
          resp: http
          private: true
          cors: true
          caching:
            enabled: true
            ttlInSeconds: 300
            cacheKeyParameters:
              - name: request.path.id

package:
  individually: true
  exclude:
    - tests/**

plugins:
  - serverless-webpack
  - serverless-api-gateway-caching
  # - serverless-domain-manager

custom:
  webpack:
    webpackConfig: 'webpack.prod.js'
    includeModules: true
    packager: 'npm'

  apiGatewayCaching:
    enabled: true
```
