### ISSUE TITLE
No Rest API found. Caching settings will not be updated. when using shared API GW

### ISSUE THREAD

**Issue by mzmiric5** [DianaIonita/serverless-api-gateway-caching#16]
There seems to be an issue with the plugin when attempting to use it with the shared API Gateway.

It looks like when using a shared API GW, defined through 
```yaml
provider:
  apiGateway:
    restApiId:
      'Fn::ImportValue': CfOutputRefFromAnotherStack
    restApiRootResourceId:
      'Fn::ImportValue': CfOutputRefFromAnotherStack
```
the plugin throws the `No Rest API found. Caching settings will not be updated.` error.

This seems to be caused by the following code:
https://github.com/DianaIonita/serverless-api-gateway-caching/blob/166bd2e0331ccfa1706165ff2a514b773c5f2033/src/apiGatewayCachingPlugin.js#L50

While the plugin seems to be referencing
`get(serverless, 'service.provider.apiGateway.restApiId');`
to get a custom API GW id, it does not seem to pass the validation (as SLS does not add an external API GW to the `service.provider.compiledCloudFormationTemplate.Resources`). Manually overiding the `restApiExists` function to return `true` successfully deploys the functions and correctly enables caching.

In addition (and this is probably out of scope of this issue and the plugin), but it would be nice to be able to apply caching settings to the individual functions without having to define the caching settings for the gateway (for uses cases where you have functions in many different serverless.yml files that you want to add caching to and an API GW defined in another service/stack).
