### ISSUE TITLE
Generate RequestParameters with invalid value, empty object

### ISSUE THREAD

**Issue by GerardPaligot** [DianaIonita/serverless-api-gateway-caching#28]
Assuming you have this lambda:

```
get-tree:
  handler: trees/handler.getTree
  events:
    - http:
        path: /v1/trees
        method: get
        private: true
        caching:
          enabled: true
          cacheKeyParameters:
            - name: request.header.x-target-country
            - name: request.queryString.store_id
        request:
          parameters:
            queryStrings:
              store_id: false
            headers:
              x-target-country: true
              channel: true
```

When serverless (with this plugin activate), the `serverless-state.json` contains this CloudFormation template:

```javascript
"ApiGatewayMethodV1TreesGet": {
  "Type": "AWS::ApiGateway::Method",
  "Properties": {
    "HttpMethod": "GET",
    "RequestParameters": {
      "method.request.header.x-target-country": true,
      "method.request.header.channel": true,
      "method.request.querystring.store_id": {}
    },
    "ResourceId": {
      "Ref": "ApiGatewayResourceV1Trees"
    },
    "RestApiId": {
      "Ref": "ApiGatewayRestApi"
    },
    "ApiKeyRequired": true,
    "AuthorizationType": "NONE",
    "Integration": {
      "IntegrationHttpMethod": "POST",
      "Type": "AWS_PROXY",
      "Uri": {
        // No interesting stuff here
      },
      "CacheKeyParameters": [
        "method.request.header.x-target-country",
        "method.request.querystring.store_id"
      ],
      "RequestParameters": {
        "integration.request.header.x-target-country": "method.request.header.x-target-country",
        "integration.request.querystring.store_id": "method.request.querystring.store_id"
      },
      "CacheNamespace": "ApiGatewayMethodV1TreesGetCacheNS"
    },
    "MethodResponses": []
  }
}
```

As you can see on the `RequestParameters` property, `method.request.querystring.store_id` key has the value `{}` but should be a boolean. Between 1.2.2 and 1.1.3, this is the only diff change (always `true` in 1.1.3).

Suppose, you just need to switch the default value [at this line](https://github.com/DianaIonita/serverless-api-gateway-caching/blob/develop/src/pathParametersCache.js#L52) from `{}` to `false` but I don't understand why `existingValue` is `null` or `undefined` for my query string.

I wanted to contribute directly to your project but you have 7 tests who fail because you assume that you are waiting a javascript object.

**Comment by DianaIonita** [comment]
Hi @GerardPaligot,

Thanks for submitting this. The syntax for defining query string parameters is this:

```
get-tree:
  handler: trees/handler.getTree
  events:
    - http:
        path: /v1/trees
        method: get
        private: true
        caching:
          enabled: true
          cacheKeyParameters:
            - name: request.header.x-target-country
            - name: request.querystring.store_id
        request:
          parameters:
            querystrings:
              store_id: false
            headers:
              x-target-country: true
              channel: true
```

Note `request.querystring.store_id` under cache key parameters and `querystrings` under request/parameters - all lower case.

The `{}` empty object is accepted by CloudFormation, it would not throw a validation exception. The value of `false` or `true` seems to only specify whether request validation is required for that parameter. When it's empty, it treats it as `false`. However, if the request parameter isn't there at all, it cannot be used as a cache key parameter. I thought I'd leave it as `{}` because the `serverless-api-gateway-caching` plugin should not be responsible for defining validation on request parameters.
Please let me know if you still run into trouble with this.
