### ISSUE TITLE
Miss from cloudfront

### ISSUE THREAD

**Issue by webchaz** [DianaIonita/serverless-api-gateway-caching#53]
Should this be showing a hit from cloudfront if configured correctly?  

This is what I have and doesn't seem to be caching:

```
custom:
  splitStacks:
    perFunction: true
    perType: true
  warmup:
    enabled: true
    events:
      - schedule: rate(15 minutes)
    prewarm: true
  apiGatewayXray: false
  baseUrl: v1
  prune:
    automatic: true
    number: 2
  apiGatewayCaching:
    enabled: true

plugins:
  - serverless-plugin-split-stacks
  - serverless-plugin-warmup
  - serverless-prune-plugin
  - serverless-api-gateway-caching
```

For functions:
```
getStats:
  handler: src/functions/reports.getStats
  events:
    - http:
        path: ${self:custom.baseUrl}/reports/stats
        method: get
        private: true
        cors: true
        caching:
          enabled: true
```

Thank you!
