### ISSUE TITLE
Support for `cacheKeyParameters` per QueryStringParameter

### ISSUE THREAD

**Issue by gligorkot** [DianaIonita/serverless-api-gateway-caching#59]
Love this plugin! It is super valuable and very quick to set up.

One thing that would be great to add is support for `queryStringParameters` in the `cacheKeyParameters` property.

Thank you!

**Comment by DianaIonita** [comment]
Thanks @gligorkot!

You should already be able to specify query string parameters as cache keys, like this:

```
# Responses are cached based on the 'breed' query string parameter
get-cats-by-breed:
  handler: rest_api/cat/get/handler.handle
  events:
    - http:
        path: /cats
        method: get
        caching:
          enabled: true
          cacheKeyParameters:
            - name: request.querystring.breed
```
