### ISSUE TITLE
Caching was not enabled following provided example

### ISSUE THREAD

**Issue by ajbazz** [DianaIonita/serverless-api-gateway-caching#6]
I installed this via npm without issue. 

Next, I followed the serverless.yml example from https://www.npmjs.com/package/serverless-api-gateway-caching, and added these to mine. 

```
  plugins:
  - serverless-domain-manager
  - serverless-api-gateway-caching

  site:
    handler: bin/details
    timeout: 30
    events:
      - http:
          path: v1/details/{detail_id}
          method: GET
          cors: true
          authorizer:
            arn: ${ssm:/serverless/global/cognito_arn}
          private: true
          cacheKeyParameters:
            - name: request.path.detail_id
              required: true
            - name: request.header.Accept-Language
              required: false 
```

I ran the serverless deploy command.
`saml2aws exec 'npm run -- serverless deploy -v'`
Again no issues. 

However when I went to the API Gateway in the AWS console, the caching option for this request was not enabled. 

It would be great if this worked as we have not had success trying other options.

**Comment by DianaIonita** [comment]
Hey @ajbazz,

It looks like you're missing a few things from configuration. Try having another go:

```
plugins:
- serverless-domain-manager
- serverless-api-gateway-caching

custom:
  apiGatewayCaching: # this enables caching globally - you need this for the plugin to be enabled
    enabled: true

functions:
  site:
    handler: bin/details
    timeout: 30
    events:
      - http:
          path: v1/details/{detail_id}
          method: GET
          cors: true
          authorizer:
            arn: ${ssm:/serverless/global/cognito_arn}
          private: true
          caching: # you need to specify cacheKeyParameters under a caching option in your function
            enabled: true # you also need to enable caching for each particular function
            cacheKeyParameters:
              - name: request.path.detail_id
                required: true
              - name: request.header.Accept-Language
                required: false
```
