### ISSUE TITLE
Problem on deploy

### ISSUE THREAD

**Issue by pedrosodre** [DianaIonita/serverless-api-gateway-caching#60]
Hello,

I tried add the serverless-api-gateway-caching to our serverless.yml to enable the caching on a path param, but the deploy returns this error on pipeline:

```
serverless deploy --stage=prd
 
  Serverless Error ---------------------------------------
 
  Serverless plugin "serverless-api-gateway-caching" initialization errored: Unexpected token (
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     OS:                     linux
     Node Version:           6.17.1
     Serverless Version:     1.42.3
```

Here is our serverless.yml:
```
service:
  name: serverless-endpoint

custom:
  apiGatewayCaching:
    enabled: true
    ttlInSeconds: 3600

plugins:
  - serverless-webpack
  - serverless-api-gateway-caching

package:
  exclude:
    - tests/**
    - doc/**

provider:
  name: aws
  region: us-east-1
  runtime: nodejs10.x
  environment:
    INDEX_LOG: logs_endpoint

functions:
  get-endpoint:
    handler: lambda/endpoint-public.get
    timeout: 30
    memorySize: 256
    events:
      - http:
          method: get
          path: /endpoint/{url}
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.path.url
```

Did I forget anything?

Cheers
