### ISSUE TITLE
clusterSize is ignored.

### ISSUE THREAD

**Issue by angelcervera** [DianaIonita/serverless-api-gateway-caching#61]
This is the config that I'm using:
```
      caching:
        enabled: true
        clusterSize: '13.5'
        ttlInSeconds: 3600
        cacheKeyParameters:
          - name: request.path.param1
          - name: request.querystring.param2
```
As result, the cache is enable correctly but the **cache capacity is 0.5 instead 13.5**

```
sls -v
1.42.3
node --version
v9.11.2

serverless-api-gateway-caching: 1.4.0
```

https://stackoverflow.com/questions/58137023/serverless-api-gateway-caching-plugin-is-not-setting-the-cache-size

**Comment by DianaIonita** [comment]
Hi @angelcervera,

You can set the `clusterSize` on the whole instance under global settings:

```yml
custom:
  apiGatewayCaching:
    enabled: true
    clusterSize: '13.5'
```

You can't define it for each function, because there's only one cache cluster for all functions associated with this Rest API.
