### ISSUE TITLE
Deployment Error when Caching Request Body on POST Method

### ISSUE THREAD

**Issue by Jordan-Eckowitz** [DianaIonita/serverless-api-gateway-caching#63]
I'm trying to enable caching on a `POST` method endpoint based on the request body. When I try and deploy I get the following error (replacing sensitive info with XXXX):

```
  Serverless Error --------------------------------------- 
  
  An error occurred: XXXX - Invalid mapping expression specified: Validation Result: warnings : [], errors : [Invalid mapping expression specified: method.request.body] (Service: AmazonApiGateway; Status Code: 400; Error Code: BadRequestException; Request ID: a86f8247-9c10-4433-964c-386d334bfd64). 
```

Here are my configuration settings for the endpoint (replacing sensitive info with XXXX):

```YAML
  events:
    - http:
        integration: lambda-proxy
        path: apps/XXXX/XXXX
        method: post
        cors: true
        authorizer:
          name: XXXX
          arn: >-
            XXXX
        caching:
          enabled: true
          cacheKeyParameters:
            - name: request.body
```

Is there something I'm missing?
