### ISSUE TITLE
Wrong status of header X-Cache: Miss from cloudfront

### ISSUE THREAD

**Issue by itsTeknas** [DianaIonita/serverless-api-gateway-caching#64]
i implemented this for a simple api in
serverless + aws lambda with caching enabled

i can confirm the responses are cached because there are no lambda execution logs for subsequent hits. But in the response, the header X-Cache says "Miss from cloudfront"

config file:
```yaml
service: survey-responce-endpoint

plugins:
  - serverless-api-gateway-caching
  - serverless-domain-manager

custom:
  customDomain:
    domainName: survey.staging.endpoint.martechsurveys.in
    basePath: 'survey'
    stage: ${self:provider.stage}
    createRoute53Record: true
  apiGatewayCaching:
    enabled: true

provider:
  name: aws
  profile: martech
  runtime: nodejs10.x
  region: ap-south-1
  memorySize: 512
  stage: ${opt:stage, 'development'}
  role: arn:aws:iam::xxxxx
  logRetentionInDays: 7
  environment:
    NODE_ENV: ${opt:stage, 'development'}

functions:

  get_survey:
    handler: handler.getSurvey
    timeout: 5
    memorySize: 128
    reservedConcurrency: 50
    events:
      - http:
          path: get_survey
          method: get
          cors: true
          caching:
            enabled: true
            ttlInSeconds: 300 # 5 mins
            cacheKeyParameters:
              - name: request.querystring.surveyId
```

handler:
```javascript
module.exports.getSurvey = async event => {
  return {
        statusCode: 200,
        headers: {
          "Content-Type": "application/json",
          "Cache-Control": "public, max-age=300, s-maxage=300",
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Credentials': true,
        },
        body: JSON.stringify({"hello":"world"}),
      };
};
```

don't know if this has anything to do with this plugin or a quirk of cloudfront.
