### ISSUE TITLE
offline mode

### ISSUE THREAD

**Issue by theskillwithin** [DianaIonita/serverless-api-gateway-caching#66]
will this cache things in `sls offline start` as well?

```
service: email-verify

frameworkVersion: '>=1.41.1 <2.0.0'

package:
  individually: true
  excludeDevDependencies: true
  exclude:
    - examples/**
    - testing

provider:
  name: aws
  runtime: nodejs12.x
  profile: foobar_serverless
  stage: ${opt:stage, 'dev'} ## Currently we support dev, stage & prod
  region: us-east-1
  currnetApiVersion: v1
  enableCrons:
    prod: true
    disable: false

  # Environment Variables
  environment:
    IS_OFFLINE: false ## set this to true if you are testing locally and are running dynamoDB
    XVERIFY_KEY: ${file(../../config.yml):XVERIFY_KEY}

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-api-gateway-caching

custom:
  apiGatewayCaching:
    enabled: true
    ttlInSeconds: 2000

functions:
  EmailVerifyProxy:
    handler: index.emailVerifyProxy
    events:
      - http:
          path: ${self:provider.currnetApiVersion}/emailVerifyProxy
          method: get
          cors: true
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.querystring.email
              - name: request.querystring.domain

```
