### ISSUE TITLE
Does not work with "serverless-aws-alias" plugin

### ISSUE THREAD

**Issue by ValeryP** [DianaIonita/serverless-api-gateway-caching#69]
I've realized that the plugin does not work for aliases. Every time I deploy to any alias it performs all actions on the stage instead of alias name.

Plugins:
```
plugins:
  - serverless-python-requirements
  - serverless-aws-alias
  - serverless-api-gateway-caching
  - serverless-api-gateway-throttling
```

Fun:
```
functions:
  energy:
    handler: src/handler.energy
    package: {}
    events:
      - http:
          path: energy
          method: get
          cors: true
          private: true
          caching:
            enabled: true
            clusterSize: '0.5'
            ttlInSeconds: 60
            perKeyInvalidation:
              requireAuthorization: true
              handleUnauthorizedRequests: Ignore
            cacheKeyParameters:
              - name: request.header.x-api-key
```

Am I doing something wrong or is there any workaround? Thanks!
