### ISSUE TITLE
multivaluequerystring fails to build

### ISSUE THREAD

**Issue by Ksmike** [DianaIonita/serverless-api-gateway-caching#70]
Hi,

Do you have an example of how to use request.multivaluequerystring -> 

I tried to deploy it and I just get this error below

```
Invalid mapping expression specified: Validation Result: warnings : [], errors : [Invalid mapping expression specified: method.request.multivaluequerystring.versionId] (Service: AmazonApiGateway; Status Code: 400; Error Code: BadRequestException; Request ID: efe76a48-f2c6-4da1-b089-d45d13330232; Proxy: null)
```
```
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.multivaluequerystring.versionId
              - name: request.multivaluequerystring._id
              - name: request.multivaluequerystring.pluginVersion
```
any info on how to use multivaluequerystring would be helpful, I have three keys i need to cache against, versionid&id& pluginVersionId

Cheers
