### ISSUE TITLE
Configuration warning unrecognized property 'caching'

### ISSUE THREAD

**Issue by EddyArellanes** [DianaIonita/serverless-api-gateway-caching#76]
With the property caching inside like this one:
```
 companies:
    handler: src/index.companiesHandler
    events:
      - http:
          path: '{version}/companies'
          method: ANY
          cors:
            origin: "*"
            headers: ${self:custom.allowed-headers}
            allowCredentials: true
          private: false
          caching:
            enabled: true #false
            ttlInSeconds: 120 #3600
            cacheKeyParameters:
              - name: request.querystring.regionId
              - name: request.querystring.skip
              - name: request.querystring.take
              - name: request.querystring.filterName
              - name: request.querystring.filterValue
```
The Service configuration validation throws  Configuration warning unrecognized property 'caching'.
According to service configuration validation page: 
_Configuration related to external plugin does not have an associated JSON Schema. In such cases, please report the issue with the plugin author and provide them the details on how to extend validation schema in order to permanently correct the issue._
