### ISSUE TITLE
cache global with ttl = 0 nor working

### ISSUE THREAD

**Issue by 91-julian-sanchez** [DianaIonita/serverless-api-gateway-caching#80]
when setup `ttlInSeconds: 0 ` and deploy code, deployed cache ttl is 3600 , because const DEFAULT_TTL = 3600; 

it is not possible to implement ttl = 0 and this can be very useful to enable global cache without storage but if cache on specific endpoints

**Comment by DianaIonita** [comment]
Hi @91-julian-sanchez,

Thanks for raising this issue.
I'm not entirely sure I understand your use-case, would you mind giving me an example of how setting TTL to 0 can help you?

**Comment by quanght55** [comment]
@DianaIonita I'm meeting this requirement too

when I enabled global caching configuration, on AWS UI I saw specific domains are inherited from global which means cache on every single one.

I try to set TTL = 0 on global and TTL = 3600 on path I want to cache but TTL = 0 is changed to 3600

**Comment by DianaIonita** [comment]
Values of zero for `ttlInSeconds` should now be supported in [v1.6.1](https://github.com/DianaIonita/serverless-api-gateway-caching/releases/tag/1.6.1)

Please note that setting `ttlInSeconds: 0` on global cache or function cache has the same effect as setting `enabled: false`. Using a boolean is the recommended way of disabling caching, because it explicitly says that caching is disabled, as opposed to having to figure that out by reading a completely different property like `ttlInSeconds`.


For example:
```yml
plugins:
  - serverless-api-gateway-caching

custom:
  apiGatewayCaching:
    enabled: true

functions:
  list-cats:
    handler: rest_api/cats/get/handler.handle
    events:
      - http:
          path: /cats
          method: get
          # caching is enabled
          caching:
            enabled: true

   update-cat:
    handler: rest_api/cat/post/handler.handle
    events:
      - http:
          path: /cat/{pawId}
          method: post
          # caching is disabled by default
```
